### ISSUE TITLE
Increase the resolution size of outputs images

### ISSUE THREAD

**Issue by mapsmak353478** [jkunimune15/Map-Projections#4]
Hello
a big thank you for this great software

the only annoying thing is the limitation of the size of the generated image... it is limited to 10000x5000 pixels (approx.)

It prevents me from generating very detailed maps... please can you increase the size of the renderings (a size of 30000 pixels would be fine)

Thanks to you

**Comment by jkunimune15** [comment]
I can. It's an arbitrary limitation, so I should be able to change it easily. Unfortunately, Oracle made some changes to Java last year that broke my executable build, so it's going to take me some time to figure out how to fix that (that's the only reason I haven't done this yet). I will get to it eventually, though--hopefully this month.

**Comment by johanjohan** [comment]
Yes Justin, thank you for the program.

some thoughts on image file sizes:

_Photoshop_ internally supports a maximum image size of 300,000 x 300,000 pixels (assuming you have enough RAM), but very few image file types support this size (see below).

_GIMP_ will actually let you create a 262,144 x 262,144 pixels canvas.

For large formats one needs to use a 64-bit version of an image editing program in order to be able to reserve the amount of memory required. 

Common _image formats_ have limitations concerning dimensions, these can change from OS to OS: 

- PNG files do not have a pixel or resolution limit.
- TIFF files do not have a pixel or resolution limit, but they do have a 4GB file size limit.
- Photoshop PSD files have a 2GB file size limit. They also have a maximum height and width of 30,000 pixels. 
- Photoshop PSB files have a limitation of 300,000 x 300,000 pixels. Use this format for very large image files.
- JPEGs have a limitation of 65,535 × 65,535 pixels and a 2GB file size limit. This is a lossy format.

**Comment by johanjohan** [comment]
Same refers to loading large images. Map-Designer does not load very large images. win 10 64, 32G Ram

**Comment by mapsmak353478** [comment]
Thank you very much for your contributions
I await with impatience. A rendering size of 50,000 pixels would be great.

> Same refers to loading large images. Map-Designer does not load very large images. win 10 64, 32G Ram

I can load MapDesignerRaster with a 211 Mb png image input with a 30292x14680 px size without any problem (it takes about 10 seconds to load it)
But when rendering I am limited to about 10000x5000 px image size

**Comment by jkunimune15** [comment]
The max image size is increased to 30 000 × 30 000 in [the latest release](https://github.com/jkunimune15/Map-Projections/releases/tag/v3.4.4). I can't go much higher before JavaFX starts having integer overflow issues, so hopefully that's enough.

**Comment by tumagonx** [comment]
At the moment I only concerned about Cahill Keyes Projection, my computer has 8gb ram, I can deal with 21600x21600 input output.

What I want though is to use that resolution as 1 octant per process only so later I can stitch them all to make 86400x43200 map (BMNG full resolution)
my workaround is to make change in PixelMap.java
double x = 0.5 + lon/(0.5*Math.PI); //only quarter width
and in octohedral.java I change the profile to process 1 pair octant instead of 4
but can I disable the inverse octant? so I have 21600x21600 output instead of 21600x43200 which not possible for my RAM?

**Comment by jkunimune15** [comment]
I just pushed an update that lets you do this.  Now, if you load an input image with the word "octant" in the filename, it will interpret the file as a single octant.  You can then use the "Cahill–Keyes (single octant)" projection under the "Polyhedral" folder to project just that octant.  You'll need to flip and/or rotate the results to stitch them together into a single map.

Does this cover the use case that you were thinking of?

**Comment by tumagonx** [comment]
yes, thank you!
